#!/usr/bin/env bash

function genesis_epub_batch()
{
    local filepath
    local filename
    local title
    local link

    for filepath in "$1"/*.pdf
    do
        filename="$(basename "$filepath")"
        filename="${filename%.*}"
        title="$(basename "$filepath" | sed -n 's/ - .*//p')"

        for link in $(genesis-epub-downloader "${title:-$filename}")
        do
            if wget -c "$link" -O "${filepath%.*}.epub"
            then
                rm "$filepath"
                break
            fi
        done
    done
}

genesis_epub_batch "$1"
